In [1]:
import numpy as np

In [2]:
d1 = np.random.random()

In [3]:
d1

0.4963381859175293

In [5]:
d2 = np.random.random()

In [7]:
d2

0.9268766642318673

In [8]:
d3 = np.random.rand()

In [9]:
d3

0.06496267289335789

In [10]:
d4 = np.random.rand(2, 3)

In [11]:
d4

array([[0.91581186, 0.75706819, 0.89259449],
       [0.63925333, 0.08407481, 0.99550635]])

In [12]:
d5 = np.random.rand(2, 4)

In [47]:
d5.ndim

2

In [13]:
d5

array([[0.23977677, 0.5220453 , 0.68823905, 0.64957033],
       [0.73233478, 0.26578454, 0.52535918, 0.77559579]])

In [14]:
d6 = np.random.rand(2, 3, 4)

In [48]:
d6.ndim

3

In [15]:
d6

array([[[0.89067167, 0.77073716, 0.9643339 , 0.16581958],
        [0.429336  , 0.01929919, 0.27614621, 0.58337157],
        [0.23423652, 0.71426358, 0.77413661, 0.33467224]],

       [[0.69944033, 0.27579478, 0.02902184, 0.40072975],
        [0.3550479 , 0.07521181, 0.34774067, 0.79344002],
        [0.18884452, 0.94446559, 0.52656633, 0.51980626]]])

In [49]:
d7 = np.random.rand(2, 3, 4, 5)

In [50]:
d7.ndim

4

In [51]:
d7.shape

(2, 3, 4, 5)

In [17]:
d7

array([[[[0.43142457, 0.61232182, 0.78997799, 0.13986751, 0.66821759],
         [0.68187887, 0.2844729 , 0.21068662, 0.24609035, 0.20133235],
         [0.69697608, 0.67903217, 0.78724186, 0.93581158, 0.47460017],
         [0.80519527, 0.3435722 , 0.18991916, 0.27450752, 0.33054122]],

        [[0.42060215, 0.9683123 , 0.5645817 , 0.01407641, 0.74473894],
         [0.66017352, 0.92426343, 0.6659168 , 0.95396552, 0.80786999],
         [0.19368091, 0.93452592, 0.87222598, 0.67232698, 0.91884269],
         [0.18914471, 0.17768333, 0.17268002, 0.66835526, 0.86722928]],

        [[0.325451  , 0.66631564, 0.12276051, 0.59556689, 0.56165927],
         [0.73124075, 0.56482727, 0.36644083, 0.02063941, 0.34790965],
         [0.01031369, 0.25392824, 0.38473413, 0.11597637, 0.98987746],
         [0.5504529 , 0.70880738, 0.89916431, 0.33041226, 0.25121589]]],


       [[[0.28137985, 0.77655984, 0.67490059, 0.75340798, 0.51566603],
         [0.67428155, 0.44873937, 0.74088629, 0.88835091, 0.43351091]

In [18]:
c1 = np.random.randn(2, 3)

In [19]:
c1

array([[-0.43620934,  0.24655092, -0.2708369 ],
       [-1.3662539 , -1.64970068, -0.35290282]])

In [20]:
c2 = np.random.randn(2, 3, 4)

In [21]:
c2

array([[[-1.83481315,  1.21522981,  0.2517858 ,  0.29031865],
        [ 1.32534059,  2.40284161,  0.88738679, -1.19411302],
        [ 1.39560164, -0.18154768,  1.14467346, -0.16709544]],

       [[ 0.40069292,  1.04965633, -0.16236043, -0.71447633],
        [ 0.33486661, -0.64511024,  1.68777981, -1.40637962],
        [ 1.57637781,  0.00667462, -0.2773807 , -1.58649466]]])

In [22]:
c3 = np.random.randrange(1, 20, 2)

AttributeError: module 'numpy.random' has no attribute 'randrange'

In [23]:
c4 = random.randrange(1, 20, 2)

NameError: name 'random' is not defined

In [24]:
import random

In [25]:
c5 = random.randrange(1, 20, 2)

In [26]:
c5

1

In [27]:
c5

1

In [28]:
c6 = random.randrange(2, 20, 5)

In [29]:
c6

17

In [30]:
d1 = np.arange(1, 3, 0.5)

In [31]:
d1

array([1. , 1.5, 2. , 2.5])

In [32]:
d2 = np.arange(3)

In [33]:
d2

array([0, 1, 2])

In [34]:
e1 = range(1, 10)

In [35]:
e1

range(1, 10)

In [36]:
list(e1)

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
e2 = np.arange(1, 10)

In [38]:
e2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
f1 = np.arange(1, 15)

In [40]:
f1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
f2 = np.arange(10, 15)

In [42]:
f2

array([10, 11, 12, 13, 14])

In [43]:
f3 = np.array(1, 2, 3, 4)

ValueError: only 2 non-keyword arguments accepted

In [ ]:
f3

In [44]:
f4 = np.array((1,2,3,4))

In [45]:
f4

array([1, 2, 3, 4])

In [46]:
f4.ndim

1

In [52]:
data1 = [6, 7.5, 8, 0, 1]

In [53]:
arra1 = np.array(data1)

In [54]:
arra1

array([6. , 7.5, 8. , 0. , 1. ])

In [55]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [56]:
arra2 = np.array(data2)

In [57]:
arra2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [59]:
arra2.ndim

2

In [60]:
arra2.shape

(2, 4)

In [62]:
arra2.dtype

dtype('int32')

In [63]:
arra1.dtype

dtype('float64')

In [64]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [67]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [68]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [69]:
np.empty((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [70]:
np.empty((3, 4, 5))

array([[[7.63354438e-313, 7.63353830e-313, 0.00000000e+000,
         0.00000000e+000, 1.05695337e-307],
        [1.15998412e-028, 2.44171989e+232, 8.00801729e+159,
         1.21359026e+132, 1.36989256e-071],
        [3.44353323e-086, 1.37099711e-071, 1.19965206e-071,
         6.03095104e-154, 5.05461236e-038],
        [6.12743486e-154, 8.09244594e-153, 1.74450868e-076,
         2.40523445e-057, 8.05795541e-096]],

       [[5.64437385e-062, 8.24227387e-072, 1.65746703e-076,
         6.01391519e-154, 4.62857235e-072],
        [1.17607307e-047, 5.04887243e-038, 1.05235611e-153,
         9.95658270e-043, 3.25266768e-086],
        [3.21930482e-057, 1.81154498e-152, 1.20336039e+132,
         4.27329872e-033, 3.44353323e-086],
        [4.67011759e-062, 8.23151147e-067, 2.48103379e-091,
         1.58767673e-047, 6.12743486e-154]],

       [[8.09244594e-153, 1.52032307e-047, 1.03277984e-047,
         9.45513597e-096, 1.04120183e-042],
        [8.24227374e-072, 1.72532309e-047, 6.01391519e-154,


In [71]:
arra1 = np.array([1, 2, 3], dtype = np.float64)

In [72]:
arra1

array([1., 2., 3.])

In [73]:
arra1.dtype

dtype('float64')

In [74]:
arra2 = np.array([1, 2, 3], dtype = np.int32)

In [75]:
arra2

array([1, 2, 3])

In [76]:
arra2.dtype

dtype('int32')

In [77]:
arr = np.array([1,2,3,4,5])

In [78]:
arr

array([1, 2, 3, 4, 5])

In [79]:
arr.dtype

dtype('int32')

In [80]:
arr1 = arr.astype(np.float64)

In [81]:
arr1

array([1., 2., 3., 4., 5.])

In [95]:
arr10 = arr.astype(float)

In [96]:
arr10

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [82]:
arr1.dtype

dtype('float64')

In [83]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [84]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [85]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [86]:
arr.dtype

dtype('float64')

In [87]:
a1 = np.array((1,2,3))

In [88]:
a1

array([1, 2, 3])

In [89]:
a2 = np.array(['1', '2', '3'])

In [90]:
a2

array(['1', '2', '3'], dtype='<U1')

In [92]:
a2 = np.array(['1', '2', '3'], dtype = np.string_)

In [93]:
a2

array([b'1', b'2', b'3'], dtype='|S1')

In [94]:
a2.astype(float)

array([1., 2., 3.])

In [97]:
int_array = np.arange(10)

In [98]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
calibers = np.array([.22, .27, .357, .38, .44, .50], dtype = np.float64)

In [100]:
calibers

array([0.22 , 0.27 , 0.357, 0.38 , 0.44 , 0.5  ])

In [101]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [102]:
arr = np.array([[1., 2., 3.],[4., 5., 6.]])

In [103]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [104]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [105]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [106]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [107]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [108]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [109]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [110]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [111]:
arr = np.arange(10)

In [112]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
arr[5]

5

In [114]:
arr[5:8]

array([5, 6, 7])

In [115]:
arr[5:8]=12

In [116]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [117]:
arr_slice = arr[5:8]

In [118]:
arr_slice

array([12, 12, 12])

In [119]:
arr_slice[1] = 12345

In [120]:
arr_slice

array([   12, 12345,    12])

In [121]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [122]:
arr_slice[:]=64

In [123]:
arr_slice

array([64, 64, 64])

In [124]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [125]:
a1 = arr[5:8].copy()

In [126]:
a1

array([64, 64, 64])

In [127]:
a1[:]=11

In [128]:
a1

array([11, 11, 11])

In [129]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [130]:
ar2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [131]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [132]:
ar2[2]

array([7, 8, 9])

In [133]:
ar2[1][1]

5

In [134]:
ar2[1,1]

5

In [135]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [136]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [137]:
arr3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [139]:
arr3[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [140]:
arr3[2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [141]:
arr3[0,1]

array([4, 5, 6])

In [142]:
arr3[0,0]

array([1, 2, 3])

In [143]:
arr3[0,0,0]

1

In [4]:
a1 = np.array([0,1,2,3,4,64,64,64,8,9])

NameError: name 'np' is not defined

In [5]:
import numpy as np

In [6]:
a1 = np.array([0,1,2,3,4,64,64,64,8,9])

In [7]:
a1

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [8]:
a1[1:6]

array([ 1,  2,  3,  4, 64])

In [9]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
a2[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [1]:
import numpy as np

In [3]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
a2[:2, 1:]

array([[2, 3],
       [5, 6]])

In [7]:
a2[1, :2]

array([4, 5])

In [8]:
a2[:2, 2]

array([3, 6])

In [9]:
a2[:, :1]

array([[1],
       [4],
       [7]])

In [11]:
a2[:3, 0]

array([1, 4, 7])

In [12]:
a2[:2, 1:] = 0

In [13]:
a2

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [14]:
names = np.array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'])

In [15]:
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [16]:
data = np.random.randn(7, 4)

In [17]:
data

array([[-0.1518112 ,  0.4434983 , -0.63900468, -0.18375001],
       [-0.11889297,  1.48658652,  0.98102537, -0.02856596],
       [ 0.40170409, -1.15083197,  0.20359651, -0.9962328 ],
       [-0.95863903,  0.06330695,  0.13072072, -0.45215926],
       [-0.33823273,  1.13883775,  0.57239464, -0.8245857 ],
       [ 1.48557247, -0.56835061, -1.30352084,  0.13793813],
       [ 1.92124165,  0.39535172, -1.42683452, -1.09891271]])

In [18]:
names == 'bob'

array([ True, False, False,  True, False, False, False])

In [19]:
data[names == 'bob']

array([[-0.1518112 ,  0.4434983 , -0.63900468, -0.18375001],
       [-0.95863903,  0.06330695,  0.13072072, -0.45215926]])

In [20]:
data[names == 'bob', 2:]

array([[-0.63900468, -0.18375001],
       [ 0.13072072, -0.45215926]])

In [21]:
data[names == 'bob', 3]

array([-0.18375001, -0.45215926])

In [22]:
names != 'bob'

array([False,  True,  True, False,  True,  True,  True])

In [23]:
data[~(names == 'bob')]

array([[-0.11889297,  1.48658652,  0.98102537, -0.02856596],
       [ 0.40170409, -1.15083197,  0.20359651, -0.9962328 ],
       [-0.33823273,  1.13883775,  0.57239464, -0.8245857 ],
       [ 1.48557247, -0.56835061, -1.30352084,  0.13793813],
       [ 1.92124165,  0.39535172, -1.42683452, -1.09891271]])

In [24]:
cond = names == 'bob'

In [25]:
data[~cond]

array([[-0.11889297,  1.48658652,  0.98102537, -0.02856596],
       [ 0.40170409, -1.15083197,  0.20359651, -0.9962328 ],
       [-0.33823273,  1.13883775,  0.57239464, -0.8245857 ],
       [ 1.48557247, -0.56835061, -1.30352084,  0.13793813],
       [ 1.92124165,  0.39535172, -1.42683452, -1.09891271]])

In [26]:
mask = (names == 'bob') | (names == 'will')

In [27]:
mask

array([ True, False,  True,  True,  True, False, False])

In [28]:
data[mask]

array([[-0.1518112 ,  0.4434983 , -0.63900468, -0.18375001],
       [ 0.40170409, -1.15083197,  0.20359651, -0.9962328 ],
       [-0.95863903,  0.06330695,  0.13072072, -0.45215926],
       [-0.33823273,  1.13883775,  0.57239464, -0.8245857 ]])

In [29]:
mask[0] = False

In [30]:
mask

array([False, False,  True,  True,  True, False, False])

In [31]:
data[mask]

array([[ 0.40170409, -1.15083197,  0.20359651, -0.9962328 ],
       [-0.95863903,  0.06330695,  0.13072072, -0.45215926],
       [-0.33823273,  1.13883775,  0.57239464, -0.8245857 ]])

In [32]:
data[data < 0] = 0

In [33]:
data

array([[0.        , 0.4434983 , 0.        , 0.        ],
       [0.        , 1.48658652, 0.98102537, 0.        ],
       [0.40170409, 0.        , 0.20359651, 0.        ],
       [0.        , 0.06330695, 0.13072072, 0.        ],
       [0.        , 1.13883775, 0.57239464, 0.        ],
       [1.48557247, 0.        , 0.        , 0.13793813],
       [1.92124165, 0.39535172, 0.        , 0.        ]])

In [34]:
data[names != 'joe'] = 7

In [35]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.48658652, 0.98102537, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.48557247, 0.        , 0.        , 0.13793813],
       [1.92124165, 0.39535172, 0.        , 0.        ]])

In [36]:
arr = np.empty((8, 4))

In [42]:
for i  in reversed(range(8)):
    arr[i] = i

In [45]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [46]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [47]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [48]:
arr = np.arange(32).reshape(8, 4)

In [49]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [51]:
a1 = arr[[1, 5, 7, 2]]

In [52]:
a1

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [53]:
a1[[0, 3, 1, 2]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [20, 21, 22, 23],
       [28, 29, 30, 31]])

In [54]:
a2 = arr[[1, 5, 7, 2], [0, 3, 1, 2]]

In [55]:
a2

array([ 4, 23, 29, 10])

In [56]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [57]:
a1 = np.range(5)

AttributeError: module 'numpy' has no attribute 'range'

In [58]:
a1 = np.random.range(5)

AttributeError: module 'numpy.random' has no attribute 'range'

In [59]:
a1 = np.arange(5)

In [60]:
a1

array([0, 1, 2, 3, 4])

In [61]:
a1.T

array([0, 1, 2, 3, 4])

In [2]:
import numpy as np

In [3]:
arr = np.arange(15).reshape(3, 5)

In [4]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [6]:
arr = np.random.randn(6,3)

In [7]:
arr

array([[-0.71498602,  0.60428001, -0.67982655],
       [-1.76299981,  1.09075969, -0.05451283],
       [-1.63989843, -1.47177224, -0.38880161],
       [ 2.78552637, -1.05154041,  0.15026448],
       [ 0.47624722,  0.79804791, -0.40436903],
       [-0.1214165 ,  1.21200617, -0.34393897]])

In [8]:
np.dot(arr.T, arr)

array([[14.30935076, -2.63768689,  1.48751365],
       [-2.63768689,  6.93260119, -0.79560976],
       [ 1.48751365, -0.79560976,  0.92069021]])

In [9]:
arr = np.arange(16).reshape(2,2,4)

In [10]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [11]:
arr.transpose(1,0,2)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [12]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [13]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [14]:
arr = np.arange(10)

In [15]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [17]:
x = np.random.randn(8)
y = np.random.randn(8)

In [18]:
x

array([-0.3838672 , -1.25693898, -0.92225452, -1.69622537,  0.867449  ,
        0.44470832,  0.35748446,  0.97473723])

In [19]:
y

array([-1.4908242 ,  0.97953549,  1.82342917, -0.80082157,  1.35302128,
        0.43871764, -0.65493373,  0.23973664])

In [20]:
np.maximum(x, y)

array([-0.3838672 ,  0.97953549,  1.82342917, -0.80082157,  1.35302128,
        0.44470832,  0.35748446,  0.97473723])

In [21]:
arr = np.random.randn(7) * 5

In [22]:
arr

array([ 3.13325275, -1.975947  ,  1.42289469,  7.13176182,  3.37387625,
       -0.69118684, -4.34832738])

In [23]:
remiander, whole_part = np.modf(arr)

In [24]:
remiander

array([ 0.13325275, -0.975947  ,  0.42289469,  0.13176182,  0.37387625,
       -0.69118684, -0.34832738])

In [25]:
whole_part

array([ 3., -1.,  1.,  7.,  3., -0., -4.])

In [26]:
arr

array([ 3.13325275, -1.975947  ,  1.42289469,  7.13176182,  3.37387625,
       -0.69118684, -4.34832738])

In [27]:
np.sqrt(arr)

C:\Users\chenguang\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([1.77009964,        nan, 1.19285149, 2.67053587, 1.83681144,
              nan,        nan])

In [28]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [29]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [30]:
cond = np.array([True, False, True, True, False])

In [31]:
result = np.where(cond, xarr, yarr)

In [32]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [33]:
arr = np.random.randn(4,4)

In [34]:
arr

array([[-0.23423629,  0.95084346, -2.22178716,  0.14743251],
       [-1.17511713,  1.04197602, -0.63218439, -2.14509581],
       [ 1.04952344,  0.87164525, -0.16718806,  1.47822997],
       [-0.40176311,  0.6127691 , -1.52664611, -0.36921992]])

In [35]:
arr > 0

array([[False,  True, False,  True],
       [False,  True, False, False],
       [ True,  True, False,  True],
       [False,  True, False, False]])

In [36]:
np.where(arr > 0, 2, -2)

array([[-2,  2, -2,  2],
       [-2,  2, -2, -2],
       [ 2,  2, -2,  2],
       [-2,  2, -2, -2]])

In [37]:
np.where(arr > 0, 2, arr)

array([[-0.23423629,  2.        , -2.22178716,  2.        ],
       [-1.17511713,  2.        , -0.63218439, -2.14509581],
       [ 2.        ,  2.        , -0.16718806,  2.        ],
       [-0.40176311,  2.        , -1.52664611, -0.36921992]])

In [38]:
arr = np.random.randn(5, 4)

In [39]:
arr

array([[-0.42258101,  2.61493997, -1.41109719, -0.01652057],
       [ 0.09255618, -1.0360103 , -0.2196173 ,  0.01468276],
       [-0.51625962,  0.84257736, -0.77250256, -0.1209195 ],
       [-0.09319971, -0.67435155,  0.08206133,  0.95972207],
       [ 1.97221442,  1.87332829, -1.39778164, -0.82083116]])

In [40]:
arr.mean()

0.04752051320505433

In [41]:
np.mean(arr)

0.04752051320505433

In [42]:
arr.sum()

0.9504102641010865

In [43]:
np.sum(arr)

0.9504102641010865

In [44]:
arr.mean(axis = 1)

array([ 0.1911853 , -0.28709717, -0.14177608,  0.06855803,  0.40673248])

In [45]:
arr.sum(axis = 0)

array([ 1.03273027,  3.62048377, -3.71893736,  0.01613359])

In [46]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])

In [47]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [48]:
np.cumsum(arr)

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [49]:
arr = np.arange(9).reshape(3, 3)

In [50]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
arr.cumsum(axis = 0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [52]:
np.cumsum(arr, axis = 0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [53]:
arr.cumsum(axis = 1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]], dtype=int32)

In [54]:
arr = np.random.randn(100)

In [55]:
(arr > 0).sum()

51

In [56]:
arr

array([ 0.96153857,  1.0727685 , -0.35552095, -0.60115801, -1.35569441,
        0.38780216,  1.26478657, -0.34210277, -1.74800675, -0.21112922,
       -0.8305057 , -0.55077743, -0.00744531, -0.8109556 , -1.44904574,
        1.26734696,  0.01225565,  1.33594998,  1.71761853,  1.54743592,
       -1.58145544, -0.83393736,  1.35330867, -0.04519612,  0.15052067,
        0.16958632, -0.05403859, -0.69221686,  1.1931215 ,  0.28369497,
       -1.87284045, -0.5826836 ,  1.53555761, -1.75815373, -0.4787107 ,
       -0.54615348,  1.65675377, -0.41149184, -0.26705195,  0.8029841 ,
       -2.16197448,  0.25993751,  0.29218452,  2.49823364,  1.40608857,
        0.00754575, -0.65278216,  0.15400111, -0.01545491, -0.67136139,
       -1.20557263, -0.39828726,  1.44626086,  0.55537903,  0.72140218,
        2.31277939,  0.0909781 ,  0.30760004, -1.04717223,  0.0975841 ,
       -1.53605684, -0.14393442,  0.13080607,  0.42433051, -0.46158329,
        0.19787063, -2.18402449,  0.84084295, -0.36732139,  0.36

In [57]:
(arr < 0).sum()

49

In [58]:
bools = np.array([False, False, True, False])

In [59]:
bools.any()

True

In [60]:
bools.all()

False

In [61]:
arr = np.random.randn(6)

In [62]:
arr

array([ 1.5849911 ,  0.36564398, -0.19262872, -0.51952665,  1.11531962,
       -1.82703094])

In [63]:
arr.sort()

In [64]:
arr

array([-1.82703094, -0.51952665, -0.19262872,  0.36564398,  1.11531962,
        1.5849911 ])

In [65]:
arr = np.random.randn(5, 3)

In [66]:
arr

array([[ 0.41787417,  0.37375714,  0.88915367],
       [-0.31646477, -1.0131387 , -0.24266164],
       [-1.21683321,  0.9711463 , -0.73379741],
       [-0.80630797,  0.71122148, -1.36202973],
       [ 0.89445232,  0.42211418,  0.78134442]])

In [67]:
arr.sort(1)

In [68]:
arr

array([[ 0.37375714,  0.41787417,  0.88915367],
       [-1.0131387 , -0.31646477, -0.24266164],
       [-1.21683321, -0.73379741,  0.9711463 ],
       [-1.36202973, -0.80630797,  0.71122148],
       [ 0.42211418,  0.78134442,  0.89445232]])

In [69]:
names = np.array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'])

In [70]:
np.unique(names)

array(['bob', 'joe', 'will'], dtype='<U4')

In [71]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [72]:
np.unique(ints)

array([1, 2, 3, 4])

In [73]:
a1 = set(names)

In [74]:
a1

{'bob', 'joe', 'will'}

In [75]:
sorted(set(names))

['bob', 'joe', 'will']

In [76]:
values = np.array([6, 0, 0, 3, 2, 5, 6])

In [77]:
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

In [78]:
arr = np.arange(10)

In [79]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
np.save('some_array', arr)

In [83]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
np.savez('array_archive.npz', a = arr, b = arr)

In [86]:
arch1['b']

NameError: name 'arch1' is not defined

In [87]:
x = np.array([[1, 2, 3], [4, 5, 6]])

In [88]:
y = np.array([[6, 23], [-1, 7], [8, 9]])

In [89]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
y

array([[ 6, 23],
       [-1,  7],
       [ 8,  9]])

In [91]:
x.dot(y)

array([[ 28,  64],
       [ 67, 181]])

In [92]:
np.dot(x, y)

array([[ 28,  64],
       [ 67, 181]])

In [93]:
y.dot(x)

array([[ 98, 127, 156],
       [ 27,  33,  39],
       [ 44,  61,  78]])

In [94]:
np.dot(y, x)

array([[ 98, 127, 156],
       [ 27,  33,  39],
       [ 44,  61,  78]])

In [95]:
x @ y

array([[ 28,  64],
       [ 67, 181]])

In [96]:
samples = np.random.normal(size = (4, 4))

In [97]:
samples

array([[-0.48202182, -0.15414358,  0.44353586, -0.19018919],
       [-0.49002396,  0.37342239,  0.07640508,  0.18394691],
       [ 1.62864483, -1.35264445,  1.4181246 ,  0.50464125],
       [ 1.9692557 ,  1.78228174,  0.9959096 ,  1.78971522]])

In [98]:
from random import normalvariate

In [99]:
N = 1000000

In [100]:
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

905 ms ± 9.12 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [101]:
%timeit np.random.normal(size = N)

36.1 ms ± 986 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [102]:
np.random.seed(513)

In [103]:
a1 = np.random.randn(4)

In [104]:
a1

array([-0.71963255,  0.29737464, -0.9391222 ,  0.3866435 ])

In [1]:
import numpy as np

In [2]:
points = np.arange(1, 3, 1)

In [3]:
points

array([1, 2])

In [4]:
x, y = np.meshgrid(points, points)

In [5]:
x

array([[1, 2],
       [1, 2]])

In [6]:
y

array([[1, 1],
       [2, 2]])

In [7]:
from numpy.linalg import inv, qr

In [18]:
X = np.arange(1,5).reshape(2,2)

In [21]:
X

array([[1, 2],
       [3, 4]])

In [19]:
mat = X.T.dot(X)

In [20]:
mat

array([[10, 14],
       [14, 20]])

In [22]:
inv(mat)

array([[ 5. , -3.5],
       [-3.5,  2.5]])

In [29]:
samples = np.random.normal(size = (4,4))

In [30]:
samples

array([[ 1.29889541,  0.56222735, -1.39282996,  0.14229154],
       [ 0.28333354, -1.34758635,  0.44744674, -1.48362127],
       [-1.78800166,  0.88380883, -0.61818774, -0.49895943],
       [ 0.18958191,  2.47611282,  0.53672022, -1.36896791]])